"""Run-table and analysis audit for the confirmatory phase."""
from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from confirmatory.analyse import analyse, read_rows


def main() -> None:
    out = ROOT / "campaigns/confirmatory/results"
    rows = read_rows(out)
    archived = json.loads((out / "analysis.json").read_text())
    with tempfile.TemporaryDirectory(prefix="aedge-confirmatory-audit-") as tmp:
        scratch = Path(tmp)
        shutil.copy2(out / "runs.csv", scratch / "runs.csv")
        recomputed = analyse(scratch)
    assert recomputed == archived
    invariant_keys = ["violations", "token_overlaps", "unauthorized_services", "cold_after_quarantine", "not_home", "late_returns", "alns_timeouts"]
    totals = {key: int(sum(float(row[key]) for row in rows)) for key in invariant_keys}
    assert all(value == 0 for value in totals.values())
    report = {"runs": len(rows), "design_complete": True, "analysis_matches": True,
              "run_table_invariants": totals,
              "raw_log_policy": "representative logs are in examples/replay; the complete logs are regenerated by the campaign runner"}
    (out / "audit.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
